# Generated by Django 5.2.4 on 2025-07-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('nome_razao_social', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Material')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('unidade_medida', models.CharField(max_length=10, verbose_name='Unidade de Medida')),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque Atual')),
            ],
            options={
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=44, unique=True, verbose_name='Número da NF-e')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total da Nota')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data da Entrada')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='estoque.fornecedor')),
            ],
            options={
                'verbose_name_plural': 'Notas Fiscais de Entrada',
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='estoque.material')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.notafiscalentrada')),
            ],
            options={
                'verbose_name_plural': 'Itens de Notas Fiscais',
                'unique_together': {('nota_fiscal', 'material')},
            },
        ),
    ]
