# Generated by Django 5.2.4 on 2025-07-10 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Retirada')),
                ('data_saida', models.DateTimeField(auto_now_add=True, verbose_name='Data da Saída')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação/Destino')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.material', verbose_name='Material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Saída de Material',
                'verbose_name_plural': 'Saídas de Materiais',
                'ordering': ['-data_saida'],
            },
        ),
    ]
