# Generated by Django 5.2.4 on 2025-07-10 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_saidamaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidamaterial',
            name='data_saida',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Saída'),
        ),
    ]
