# Generated by Django 5.2.4 on 2025-07-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_saidamaterial_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('L', 'Litro'), ('M', 'Metro'), ('M3', 'Metro Cúbico')], default='UN', max_length=2, verbose_name='Unidade de Medida'),
        ),
    ]
