# Generated by Django 5.2.4 on 2025-07-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
